package model;

public enum CellState {
    PLAYER1, KING_PLAYER1, QUEEN_PLAYER1, ROOK_PLAYER1, BISHOP_PLAYER1, 
    KNIGHT_PLAYER1, PAWN_PLAYER1, EMPTY, KING_PLAYER2, QUEEN_PLAYER2,
    ROOK_PLAYER2, BISHOP_PLAYER2, KNIGHT_PLAYER2, PAWN_PLAYER2, PLAYER2
}
